### ISSUE TITLE
changed google API

### ISSUE THREAD

**Issue by sohamakl** [visionect/roombooking#6]
Hello Visionect,

it looks like google has changed something on its API. The id_token isn't a standard return value anymore and  https://www.googleapis.com/auth/userinfo.email is set to obsolete.

In my case playing around with roombooking end up always with the same error:
#500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

```
Traceback (most recent call last):
  File "/home/parallels/roombooking/virt/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/home/parallels/roombooking/virt/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/parallels/roombooking/virt/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "server.py", line 91, in auth
    storage = SqliteStorage(credentials.id_token['id'])
KeyError: 'id'
```

I don't have enough personal experience to adapt your code to the new requirements and hopefuly ask for some hints our a redesign of the current release.

Cheers - Mark

**Comment by 0raid** [comment]
did you find any solution? i have the same issue....
